export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS'
export const FETCH_ALL_POSTS_SUCCESS = 'FETCH_ALL_POSTS_SUCCESS'
export const FETCH_ALL_POSTS_FAIL = 'FETCH_ALL_POSTS_FAIL'

export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS'

export const FETCH_INTERVAL_ID = 'FETCH_INTERVAL_ID'
